# This is the default config file.
# It also shows all the default values, if you don't create the file.

# All URL values may omit the scheme and/or port, as well as the beginning double slash
# Valid URL examples:
# gemini://example.com
# //example.com
# example.com
# example.com:123


[a-general]
# Press Ctrl-H to access it
home = "gemini://gemini.circumlunar.space/capcom/"

# Follow up to 5 Gemini redirects without prompting.
# A prompt is always shown after the 5th redirect and for redirects to protocols other than Gemini.
# If set to false, a prompt will be shown before following redirects.
auto_redirect = false

# What command to run to open a HTTP(S) URL. Set to "default" to try to guess the browser,
# or set to "off" to not open HTTP(S) URLs.
# If a command is set, than the URL will be added (in quotes) to the end of the command.
# A space will be prepended if necessary.
http = "/opt/firefoxnightly/firefox"

# Any URL that will accept a query string can be put here
search = "gemini://gus.guru/search"

# Whether colors will be used in the terminal
color = true

# Whether to replace list asterisks with unicode bullets
bullets = true

# A number from 0 to 1, indicating what percentage of the terminal width the left margin should take up.
left_margin = 0.15

# The max number of columns to wrap a page's text to. Preformatted blocks are not wrapped.
max_width = 100

# 'downloads' is the path to a downloads folder.
# An empty value means the code will find the default downloads folder for your system.
# If the path does not exist it will be created.
downloads = "/home/edouard/downloads/amfora/" 

# Max size for displayable content in bytes - after that size a download window pops up
page_max_size = 2097152  # 2 MiB
# Max time it takes to load a page in seconds - after that a download window pops up
page_max_time = 10

# Whether to replace tab numbers with emoji favicons, which are cached.
emoji_favicons = false

[auth]
# Authentication settings

[auth.certs]
# Client certificates
# Set domain name equal to path to client cert
# "example.com" = "mycert.crt"
"astrobotany.mozz.us" = "/home/edouard/.local/share/amfora/gemcert.pem"

[auth.keys]
# Client certificate keys
# Set domain name equal to path to key for the client cert above
# "example.com" = "mycert.key"
"astrobotany.mozz.us" = "/home/edouard/.local/share/amfora/gemkey.pem"

[keybindings]
# In the future there will be more settings here.

# Hold down shift and press the numbers on your keyboard (1,2,3,4,5,6,7,8,9,0) to set this up.
# It is default set to be accurate for US keyboards.
shift_numbers = "!@#$%^&*()"


[url-handlers]
# Allows setting the commands to run for various URL schemes.
# E.g. to open FTP URLs with FileZilla set the following key:
#   ftp = "filezilla"
# You can set any scheme to "off" or "" to disable handling it, or
# just leave the key unset.
#
# DO NOT use this for setting the HTTP command.
# Use the http setting in the "a-general" section above.
#
# NOTE: These settings are override by the ones in the proxies section.

# This is a special key that defines the handler for all URL schemes for which
# no handler is defined.
other = "off"


[cache]
# Options for page cache - which is only for text/gemini pages
# Increase the cache size to speed up browsing at the expense of memory

# Zero values mean there is no limit
max_size = 0  # Size in bytes
max_pages = 30 # The maximum number of pages the cache will store


[proxies]
# Allows setting a Gemini proxy for different schemes.
# The settings are similar to the url-handlers section above.
# E.g. to open a gopher page by connecting to a Gemini proxy server:
#   gopher = "example.com:123"
#
# Port 1965 is assumed if no port is specified.
#
# NOTE: These settings override any external handlers specified in
# the url-handlers section.
#
# Note that HTTP and HTTPS are treated as separate protocols here.
https = "low-key.me:1966"
http = "low-key.me:1966"
gopher = "low-key.me:1967"

[theme]

# UI
bg = "#1f1f28"
tab_num = "#7fb4ca"
tab_divider = "#54546d"
bottombar_label = "#dcd7ba"
bottombar_text = "#dcd7ba"
bottombar_bg = "#363646"
scrollbar = "#54546d"

# Gemtext highlighting
hdg_1 = "#957fb8"
hdg_2 = "#7e9cd8"
hdg_3 = "#7fb4ca"
amfora_link = "#68ad99"
foreign_link = "#c0a36e"
link_number = "#98bb6c"
regular_text = "#dcd7ba"
quote_text = "#c8c093"
preformatted_text = "#727169"
list_text = "#dcd7ba"

# Dialog boxes
btn_bg = "#363646"
btn_text = "#dcd7ba"
dl_choice_modal_bg = "#363646"
dl_choice_modal_text = "#dcd7ba"
dl_modal_bg = "#363646"
dl_modal_text = "#dcd7ba"
info_modal_bg = "#363646"
info_modal_text = "#dcd7ba"
error_modal_bg = "#e46876"
error_modal_text = "#1f1f28"
yesno_modal_bg = "#363646"
yesno_modal_text = "#dcd7ba"
tofu_modal_bg = "#363646"
tofu_modal_text = "#dcd7ba"
subscription_modal_bg = "#363646"
subscription_modal_text = "#dcd7ba"

# Input
input_modal_bg = "#363646"
input_modal_text = "#dcd7ba"
input_modal_field_bg = "#54546d"
input_modal_field_text = "#dcd7ba"

# Bookmarking
bkmk_modal_bg = "#363646"
bkmk_modal_text = "#dcd7ba"
bkmk_modal_label = "#dcd7ba"
bkmk_modal_field_bg = "#54546d"
bkmk_modal_field_text = "#dcd7ba"
